sudo: false
language: ruby
go:
  - 1.13
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem install bundler
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.13 bash)"
install:
  - bundle install
  - bundle exec rake compile
script:
  - bundle exec rake
  - bundle exec ataru check
